version: '3.8'

services:
  gardena2mqtt:
    image: mcr.microsoft.com/devcontainers/python:3
    volumes:
      - ..:/app:cached

    # load environment variables from devcontainer.env
    env_file: devcontainer.env

    # Overrides default command so container keep running indefinitely
    entrypoint: sleep infinity

    # Runs app on the same network as the mosquitto container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped

    # Add "forwardPorts": ["1883"] to **devcontainer.json** to forward mosquitto locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)